[project]
name = "klein-clone"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.4",
    "pillow>=11.3.0",
]

[dependency-groups]
dev = [
    "ruff==0.12.7",
]
